[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "epowcore"
version = "0.1.0"
description = "A converter between different power system model formats and a generic data format."
requires-python = ">=3.11,<3.12"
authors = [
    {name = "KIT-IAI-ESA"},
]
license = {text = ""}
dependencies = [
    "dataclasses",
    "geojson",
    "networkx",
    "matplotlib",
    "scipy",
    "pyyaml",
    "pandapower==2.14.11",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "mypy",
    "sphinx",
    "sphinx_rtd_theme",
    "pylint",
    "isort",
    "pre-commit",
]
pypsa = [
    "pypsa>=0.35.2",
]
simscape = [
    "matlabengine==9.13.9",
]

[tool.setuptools.packages.find]
include = ["epowcore", "epowcore.*"]

[tool.setuptools]
zip-safe = false
